In [3]:
!pip install jupyter_contrib_nbextensions

     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     --------------------------------------- 0.0/23.5 MB 388.9 kB/s eta 0:01:01
     --------------------------------------- 0.0/23.5 MB 388.9 kB/s eta 0:01:01
     --------------------------------------- 0.1/23.5 MB 847.9 kB/s eta 0:00:28
     --------------------------------------- 0.2/23.5 MB 654.6 kB/s eta 0:00:36
      --------------------------------------- 0.4/23.5 MB 1.4 MB/s eta 0:00:17
      --------------------------------------- 0.5/23.5 MB 1.5 MB/s eta 0:00:16
     - -------------------------------------- 0.6/23.5 MB 1.8 MB/s eta 0:00:13
     - -------------------------------------- 1.0/23.5 MB 2.4 MB/s eta 0:00:10
     - -------------------------------------- 1.1/23.5 MB 2.5 MB/s eta 0:00:09
     - -------------------------------------- 1.1/23.5 MB 2.5 MB/s eta 0:00:09
     -- ------------------------------------- 1.3/23.5 MB 2.4 

In [4]:
!jupyter contrib nbextension install -user

usage: jupyter-contrib.EXE [-h] [--debug] [--user] [--system] [--sys-prefix]
                           [--overwrite] [--symlink] [--skip-running-check]
                           [--perform-running-check] [-s] [--only-config]
                           [--only-files]
                           [--prefix InstallContribNbextensionsApp.prefix]
                           [--nbextensions InstallContribNbextensionsApp.nbextensions_dir]
                           [extra_args ...]
jupyter-contrib.EXE: error: argument -user: expected one argument


In [6]:
!jupyter contrib nbextension install --user

[I 12:33:09 InstallContribNbextensionsApp] jupyter contrib nbextension install --user
[I 12:33:09 InstallContribNbextensionsApp] Installing jupyter_contrib_nbextensions nbextension files to jupyter data directory
[I 12:33:09 InstallContribNbextensionsApp] Installing C:\Users\bulen\anaconda3\Lib\site-packages\jupyter_contrib_nbextensions\nbextensions\addbefore -> addbefore
[I 12:33:09 InstallContribNbextensionsApp] Making directory: C:\Users\bulen\AppData\Roaming\jupyter\nbextensions\addbefore\
[I 12:33:09 InstallContribNbextensionsApp] Copying: C:\Users\bulen\anaconda3\Lib\site-packages\jupyter_contrib_nbextensions\nbextensions\addbefore\addbefore.yaml -> C:\Users\bulen\AppData\Roaming\jupyter\nbextensions\addbefore\addbefore.yaml
[I 12:33:09 InstallContribNbextensionsApp] Copying: C:\Users\bulen\anaconda3\Lib\site-packages\jupyter_contrib_nbextensions\nbextensions\addbefore\icon.png -> C:\Users\bulen\AppData\Roaming\jupyter\nbextensions\addbefore\icon.png
[I 12:33:09 InstallContribNbe

In [7]:
!jupyter nbextension enable varInspector/main

Enabling notebook extension varInspector/main...
      - Validating: ok


# Comprehension kısa yazma

## List Comprehension

In [2]:
örnek_liste = [1,2,3,4,5,6,7,8,9,10]
örnek_liste

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
kareleri_listesi = []
for i in örnek_liste:
    kareleri_listesi.append(i**2)
print(kareleri_listesi)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [1]:
pip install jupyterlab_tabnine

     ---------------------------------------- 0.0/178.9 kB ? eta -:--:--
     -- ------------------------------------- 10.2/178.9 kB ? eta -:--:--
     ------ ------------------------------ 30.7/178.9 kB 435.7 kB/s eta 0:00:01
     ------------------- ----------------- 92.2/178.9 kB 585.1 kB/s eta 0:00:01
     -----------------------------------  174.1/178.9 kB 876.1 kB/s eta 0:00:01
     ------------------------------------ 178.9/178.9 kB 902.1 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [3]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [4]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
print(a.size)

12


In [6]:
print(a.shape)

(3, 4)


In [3]:
kareleri_listesi = []
for i in örnek_liste:
    kareleri_listesi.append(i**2)
print(kareleri_listesi)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


## normal    for kısaltması


In [4]:
kareler_listesi = [i**2 for i in örnek_liste]
print(kareler_listesi)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [5]:
örnek_liste = list(range(0,11))
örnek_liste

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## for  ve if birlikte kısaltması

In [26]:
çift_sayılar = []
for i in örnek_liste:
    if i%2==0:  # == karşılaştırma opreatorudür.
        çift_sayılar.append(i)
print(çift_sayılar)

[0, 2, 4, 6, 8, 10]


In [27]:
çift_sayılar = [i for i in  örnek_liste if i%2 == 0]
çift_sayılar

[0, 2, 4, 6, 8, 10]

In [28]:
#pip install jupyterlab-spellchecker

  Obtaining dependency information for jupyterlab-spellchecker from https://files.pythonhosted.org/packages/08/54/b3d575124fa9404ceef40728f205d033fe52cf417a2245c5d108afe728e8/jupyterlab_spellchecker-0.8.4-py3-none-any.whl.metadata
  Obtaining dependency information for jupyter-server<3,>=2.0.1 from https://files.pythonhosted.org/packages/96/a2/b432812537beaf22a9dbc0d50cb62471e57ef90df42738675760fb3dce98/jupyter_server-2.7.3-py3-none-any.whl.metadata
  Obtaining dependency information for jupyterlab<5,>=4 from https://files.pythonhosted.org/packages/08/fa/b3c7d72df1f323483ae5107ad6036b9d06f677deff2aa51ac7e2b676720a/jupyterlab-4.0.7-py3-none-any.whl.metadata
  Obtaining dependency information for overrides from https://files.pythonhosted.org/packages/da/28/3fa6ef8297302fc7b3844980b6c5dbc71cdbd4b61e9b2591234214d5ab39/overrides-7.4.0-py3-none-any.whl.metadata
  Obtaining dependency information for pyzmq>=24 from https://files.pythonhosted.org/packages/83/ae/c10d71a73b190392a93ace41c789cd6c

In [29]:
#pip install aquirdturtle_collapsible_headings

     ---------------------------------------- 0.0/42.9 kB ? eta -:--:--
     ------------------ ------------------- 20.5/42.9 kB 640.0 kB/s eta 0:00:01
     --------------------------- ---------- 30.7/42.9 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 42.9/42.9 kB 418.4 kB/s eta 0:00:00
  Obtaining dependency information for jupyterlab==3.*,>=3.0.0rc13 from https://files.pythonhosted.org/packages/4e/f3/be0f5e5e0f4fee701aaa62ed44b3fe590d0af27d52bab7832ece9d81c727/jupyterlab-3.6.6-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/8.9 MB 1.7 MB/s eta 0:00:06
    --------------------------------------- 0.1/8.9 MB 1.4 MB/s eta 0:00:07
   - -------------------------------------- 0.3/8.9 MB 1.8 MB/s eta 0:00:05
   -- ------------------------------------- 0.5/8.9 MB 2.6 MB/s eta 0:00:04
   -- ------------------------------------- 0.5/8.9 MB 2.1 MB/s eta 0:00:05
   --- ----------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyterlab-spellchecker 0.8.4 requires jupyterlab<5,>=4, but you have jupyterlab 3.6.6 which is incompatible.


In [9]:
örnek_liste

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
[i**2 for i in örnek_liste if i%2 == 0]

[0, 4, 16, 36, 64, 100]

In [7]:
# 5 ten büyük  tek sayıları almak için

In [8]:
[i**2 for i in örnek_liste if i>5 and i%2!=0]

[49, 81]

## if else

In [11]:
["çift" if i%2==0 else "tek" for i in örnek_liste]

['çift',
 'tek',
 'çift',
 'tek',
 'çift',
 'tek',
 'çift',
 'tek',
 'çift',
 'tek',
 'çift']

In [13]:
tek_çift =["çift" if i%2==0 else "tek" for i in örnek_liste]
print(tek_çift)

['çift', 'tek', 'çift', 'tek', 'çift', 'tek', 'çift', 'tek', 'çift', 'tek', 'çift']


## Nested list   düzleştirme

In [14]:
nested_list =[[1,2,3],[4,5,6],[7,8,9]]
print(nested_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [20]:
for liste in nested_list:
    print(liste)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [22]:
flatten_list = []
for liste in nested_list:
    for i in liste:
        flatten_list.append(i)
print(flatten_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [24]:
[liste for liste in  nested_list]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
[i for liste in nested_list for i in liste ]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
flatten_list =[i for liste in nested_list for i in liste]  # okunaklı  gösterim için
print(*flatten_list)

1 2 3 4 5 6 7 8 9


In [27]:
flatten_list = []
for  liste in nested_list:  # iki nokta pythonda   kod bloğu başlayacak anlamına geliyor.
    for i in liste:
        if i%2 == 0:
            flatten_list.append(i)
print(flatten_list)

[2, 4, 6, 8]


In [28]:
[i for  liste in  nested_list for i in liste if i%2 == 0] #   if nor i%2  şeklindede gösterim yapabiliriz.

[2, 4, 6, 8]

In [ ]:
## örnek 

In [29]:
nested_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:


for liste in nested_list:
    for i in liste:
        if i%2 == 0:
            print("çift")
        else :
            print("tek")
print(nested_list)

tek
çift
tek
çift
tek
çift
tek
çift
tek
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [34]:
tek_çift =[]
for i in liste:
    temp =[] #geçici bir listede tuttuk önce  iç listdlerdeki  değrleri döndürüyoruz sonra  ilk for  ile  liste yapırını kruyoruz. appende
    for j in liste:
        if j%2 == 0:
            temp.append("çift")
        else:
            temp.append("tek")
    tek_çift.append(temp)
print(tek_çift)

[['tek', 'çift', 'tek'], ['tek', 'çift', 'tek'], ['tek', 'çift', 'tek']]


In [35]:
[["çift" if  j == 0 else "tek" for j in i] for i in nested_list ]

[['tek', 'tek', 'tek'], ['tek', 'tek', 'tek'], ['tek', 'tek', 'tek']]

In [ ]:
# 1. ders 55 . dak. kaldım

##   2. ders dictionary comprehension sözlük  üretecleri 

In [4]:
örnek_liste 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# output {1: "tek", 2: "çift"}

In [5]:
# önce  for la yaptık burada   sözlük oluşturuyoruz

In [6]:
tek_çift = {}
for i in örnek_liste:
    if i%2 == 0:
        tek_çift[i] = "çift"
    else:
        tek_çift[i] = "tek" 
print(tek_çift)

{1: 'tek', 2: 'çift', 3: 'tek', 4: 'çift', 5: 'tek', 6: 'çift', 7: 'tek', 8: 'çift', 9: 'tek', 10: 'çift'}


In [ ]:
# { kuşul if -- else   for i in  örnek_liste} # süslü parantez ekeldik burada  key e ihtiyaç var  i yi en başa yazıyoruz.

In [9]:
tek_çift ={i: "çift" if i%2 == 0 else "tek" for i in örnek_liste} #  başa key değerini  ekledik i: ile
print(tek_çift)

{1: 'tek', 2: 'çift', 3: 'tek', 4: 'çift', 5: 'tek', 6: 'çift', 7: 'tek', 8: 'çift', 9: 'tek', 10: 'çift'}


# Hata Yakalama

In [ ]:
# hataları son kullanıcıya  vermeyiz.

In [10]:
bölünen = 10 
bölen = 2 
bölüm = bölünen / bölen
print(bölüm)

5.0


In [11]:
bölünen = 10 
bölen = 0 
bölüm = bölünen / bölen
print(bölüm)

ZeroDivisionError: division by zero

## try pass

In [ ]:
try:
    pass
exept:
    pass

In [12]:
try :
        bölünen = 10 
        bölen = 0 
        bölüm = bölünen / bölen
        print(bölüm)
        
except ZeroDivisionError: # hatayı yakalasın
    print("Sıfır ile bölme yapılamaz!")


Sıfır ile bölme yapılamaz!


In [13]:
        bölünen = 10 
        bölen = 0 
        bölüm = bölünen / bölen
        print(bölüm)

ZeroDivisionError: division by zero

In [14]:
bölünen = 10
x 
bölen = 0
try:
    bölüm = bölünen/bölen
except ZeroDivisionError:
    print("Hata!!!")

NameError: name 'x' is not defined

In [ ]:
# neden  try  try except te gitmedi . hatayı yakalyamadı  çünkü try iöine yazmalıydık.

In [15]:
try:
     x 
except NameError:
    print("hata")

hata


In [16]:
try:
    bölünen = 10
    x 
    bölen = 0
    bölüm = bölünen /bölen
except ZeroDivisionError:
    print("Hata") # hatayı yaklamdık yine   çünkü name error   yakalmalıydıkk

NameError: name 'x' is not defined

In [17]:
try:
    bölünen = 10
    x 
    bölen = 0
    bölüm = bölünen /bölen
except ZeroDivisionError:
    print("Hata") # hatayı yaklamdık yine 
except NameError:
    print("Tanımlanamayan değişken")

Tanımlanamayan değişken


### ptyhon kütüphane dökümanlarda   hata yakalma türleri

In [ ]:
try:
    bölünen = 10
    x 
    bölen = 0
    bölüm = bölünen /bölen
except ZeroDivisionError:
    print("Hata, sıfır ile bölme  yapılamaz") # hatayı yaklamdık yine 
except NameError:
    print("Tanımlanamayan değişken")
    x = bölünen 

In [1]:
isim = "Ahmet"
isim[5]

IndexError: string index out of range

In [6]:
try:
    bölünen = 10 
    isim = "ahmet" 
    bölen = 0
    isim[5] # bu hata    işlemden önce olduğu için  yakaldı
    bölüm = bölüm / bölen # bu hata yakalanmadı
except ZeroDivisionError:
        print("sıfır ile bölünme yapılamaz.")
except NameError:
    print("tanımlanamayan değişken")
    x = bölünen
except IndexError :
    print("hata index error")

hata index error


In [9]:
try:
    bölünen = 10 
    isim = "ahmet" 
    bölen = 0
    bölüm = bölüm / bölen # bu hata yakalanmadı
    isim[5] # bu hata    işlemden önce olduğu için  yakaldı
    x
except ZeroDivisionError:
    print("sıfır ile bölünme yapılamaz.")
except NameError:
    print("tanımlanamayan değişken")
except IndexError :
    print("hata index error")

tanımlanamayan değişken


In [14]:
try:
    bölünen = 10 
    isim = "ahmet" 
    bölen = 0
    bölüm = bölünen / bölen 
    isim[5] 
    x
except ZeroDivisionError:
    print("sıfır ile bölünme yapılamaz.") # burada  hatayı yakaldık fajat programı devam ettrimek için    yeni bir değişlenverdik 
    bölen = 2 
except NameError:
    print("tanımlanamayan değişken")
except IndexError :
    print("hata index error")
print(f"prgram çalışmaya devam ediyor,  bölüm : {bölünen / bölen}")

sıfır ile bölünme yapılamaz.
prgram çalışmaya devam ediyor,  bölüm : 5.0


In [ ]:
1:41  öngörülemeyen hatada kaldım vvvv  

## finally,

In [ ]:
try:
    pass
except:
    pass
finally:
    pass

In [4]:
try:
    bölünen = 10 
    bölen = 0
    bölüm = bölünen / bölen 
    isim[5] 
    
except ZeroDivisionError:
    print("sıfır ile bölünme yapılamaz.") # burada  hatayı yakaldık fajat programı devam ettrimek için    yeni bir değişlenverdik 
    bölen = 2 
except NameError:
    print("tanımlanamayan değişken")
except IndexError :
    print("hata index error")
except:
    print("tüm hataları  burada ayıklıyoruz")
finally:      # hata lasakta almasakta  çalışır.
    print("her durumda çalışır")


sıfır ile bölünme yapılamaz.
her durumda çalışır


In [ ]:
1:59 dak.

In [ ]:
try:
    pass
except:
    pass
else:
    pass
finally:
    pass

In [1]:
try:
    bölünen = 10 
    bölen = 2
    bölüm = bölünen / bölen 
    print("bölüm:", bölüm)
   
    
except ZeroDivisionError:
    print("sıfır ile bölünme yapılamaz.") # burada  hatayı yakaldık fajat programı devam ettrimek için    yeni bir değişlenverdik 
    bölen = 2 
else:
    print("else bloğu çalıştı")
finally: 
    print() # hata lasakta almasakta  çalışır.
    print("her durumda çalışır")

bölüm: 5.0
else bloğu çalıştı

her durumda çalışır
